language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

script: "python simple_tests.py"

notifications:
  email:
    recipients:
        - fehrtj1@gcc.edu

    on_success: never
    on_failure: always
